title: BUGS - NYU
description: ...
url: "https://bugs-nyu.github.io"
markdown: kramdown
plugins: [jekyll-paginate]

# Edit this if you'd like to check out the site on your own fork
baseurl: "" # the subpath of your site, e.g. /blog

paginate: 6
paginate_path: "/news/page:num/"

collections:
  events:
    output: true
    permalink: /calendar/:path/
  projects:
    output: false # permalink: /projects/:path/
  contributors:
    output: false # permalink: /about/:path/

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "events"
    values:
      layout: "event"
