highlighter: rouge
themeColor: #7cbaff

title: BUGS NYU
email:
description: ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "bugs-nyu.github.io" # the base hostname & protocol for your site, e.g. http://example.com

plugins: [jekyll-paginate]

paginate: 6
paginate_path: "news/page:num/"

collections:
  events:
    output: true
    permalink: /events/:path/
  projects:
    output: true
    permalink: /projects/:path/



# Build settings
markdown: kramdown
