highlighter: rouge
themeColor: #7cbaff

title: BUGS NYU
email:
description: ...
baseurl: /bugs-nyu.github.io # the subpath of your site, e.g. /blog
url: https://www.kleinjdavid.com # the base hostname & protocol for your site, e.g. http://example.com

plugins: [jekyll-paginate]

paginate: 6
paginate_path: "/news/page:num/"

collections:
  events:
    output: true
    permalink: /calendar/:path/
  projects:
    output: true
    permalink: /projects/:path/


# Build settings
markdown: kramdown
