highlighter: rouge
themeColor: #7cbaff

title: BUGS NYU
email:
description: ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins: [jekyll-paginate]

paginate: 6
paginate_path: "/news/page:num/"

collections:
  events:
    output: true
    permalink: /calendar/:path/
  projects:
    output: true
    permalink: /projects/:path/
  eboard:
    output: true
    permalink: /about/:path/

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      type: "pages"
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "events"
    values:
      layout: "event"
  -
    scope:
      type: "projects"
    values:
      layout: "project"
