title: BUGS - NYU
email: bugscommunicationsteam@gmail.com
description: >-
  NYU BUGS is the open source club at NYU. We promote open source by engaging students
  through collaborative projects, hosting industry professions, and running open
  source workshops.
url: "https://bugs-nyu.github.io"
repository_url: https://github.com/BUGS-NYU/bugs-nyu.github.io
org_url: https://github.com/BUGS-NYU/
markdown: kramdown

# Edit this if you'd like to check out the site on your own fork
baseurl: "/bugs-nyu.github.io" # the subpath of your site, e.g. /blog
calendar_embed:
  xs: "https://calendar.google.com/calendar/embed?height=400&amp;wkst=1&amp;bgcolor=%23f2f2f2&amp;ctz=America%2FNew_York&amp;src=MXJnMXZhOGhpamttNzMydGE0ajQ0bGJjaDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%239E69AF&amp;showTitle=0&amp;showPrint=0&amp;showCalendars=0&amp;showTabs=0&amp;showDate=0&amp;showNav=0&amp;mode=AGENDA"
  sm: "https://calendar.google.com/calendar/embed?height=500&amp;wkst=1&amp;bgcolor=%23f2f2f2&amp;ctz=America%2FNew_York&amp;src=MXJnMXZhOGhpamttNzMydGE0ajQ0bGJjaDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%239E69AF&amp;showTitle=0&amp;showPrint=0&amp;showCalendars=0&amp;showTabs=0&amp;showDate=0&amp;showNav=0&amp;mode=AGENDA"
  md: "https://calendar.google.com/calendar/embed?height=500&amp;wkst=1&amp;bgcolor=%23f2f2f2&amp;ctz=America%2FNew_York&amp;src=MXJnMXZhOGhpamttNzMydGE0ajQ0bGJjaDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%239E69AF&amp;showTitle=0&amp;showPrint=0&amp;showCalendars=0&amp;showTabs=0&amp;showDate=0&amp;showNav=0"
  lg: "https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23f2f2f2&amp;ctz=America%2FNew_York&amp;src=MXJnMXZhOGhpamttNzMydGE0ajQ0bGJjaDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%239E69AF&amp;showTitle=0&amp;showPrint=0&amp;showCalendars=0&amp;showTabs=0&amp;showDate=0&amp;showNav=0"

future: true

# -- Collection settings --
collections: # ~ sign in yaml means null
  events: ~
  contributors:
    order:
      - varvind.md
      - anachiappan.md
      - jklukowska.md
      - araghunath.md
      - dklein.md
      - ndewji.md
  debug:
    output: true
    permalink: /debug/:slug

defaults:
  -
    scope:
      type: "debug"
    values:
      layout: "debug"
  -
    scope:
      type: "pages"
    values:
      layout: "page"
